version: "2.3"
services:
  webapp:
    image: obeliks4j-classla-stanfordnlp:latest
    #runtime: nvidia
    ports:
        - 127.0.0.1:5000:5001
    #environment:
    #    - NVIDIA_VISIBLE_DEVICES=all
